### ISSUE TITLE
It doesn't work :(

### ISSUE THREAD

**Issue by AverageComet250** [utilForever/minecraft-rs#1]
I clone the repo and run ./make but it don't work pls hep me I am 9 year old kid who want to play Minecraft for free

/s

**Comment by hardBSDk** [comment]
It was created recently, there's no code/build system yet.

This reimplementation is more complete:

https://github.com/ddevault/TrueCraft

**Comment by utilForever** [comment]
@AverageComet250 I haven't started working on this project yet. Therefore, it would be nice to look for other projects first.
@hardBSDk Thanks! :D
